module.exports = [
  // ================= આવક (AAVAK) =================
  { name: "ઘર વેરો", type: "aavak" },
  { name: "સા.પા વેરો", type: "aavak" },
  { name: "ખા.પા વેરો", type: "aavak" },
  { name: "સફાઈ વેરો", type: "aavak" },
  { name: "સફાઇ વેરો", type: "aavak" },
  { name: "ગટર વેરો", type: "aavak" },
  { name: "લાઈટ વેરો", type: "aavak" },
  { name: "કુંડી વેરો", type: "aavak" },
  { name: "સ્પેસિયલ પાણી ફી", type: "aavak" },
  { name: "વ્યવસાય વેરો", type: "aavak" },
  { name: "નળ કનેક્શન ફી", type: "aavak" },
  { name: "ગટર કનેક્શન ફી", type: "aavak" },
  { name: "જન્મ-મરણ ફી", type: "aavak" },
  { name: "ખાસ બાંઘ કામ પાણી ફી", type: "aavak" },
  { name: "સફાઈ ગ્રાન્ટ", type: "aavak" },
  { name: "બેંક વ્યાજ આવક", type: "aavak" },
  { name: "એમ.એલ.એ ગ્રાન્ટ", type: "aavak" },
  { name: "એમ.પી ગ્રાન્ટ", type: "aavak" },
  { name: "૧૫% વિવેકાધીન યોજના ગ્રાન્ટ", type: "aavak" },
  { name: "જીલ્લા પંચાયત સ્વ ભંડોળ ગ્રાન્ટ", type: "aavak" },
  { name: "તાલુકા પંચાયત સ્વ ભંડોળ ગ્રાન્ટ", type: "aavak" },
  { name: "જીલ્લા વિકાસ ફંડ ગ્રાન્ટ", type: "aavak" },
  { name: "તાલુકા વિકાસ ફંડ ગ્રાન્ટ", type: "aavak" },
  { name: "રેતી કાંકરી ગ્રાન્ટ", type: "aavak" },
  { name: "ઔડા સદભાવના ગ્રાન્ટ", type: "aavak" },
  { name: "એ.ટી.વી.ટી ગ્રાન્ટ", type: "aavak" },
  { name: "ઓ.એન.જી.સી ગ્રાન્ટ", type: "aavak" },
  { name: "લોકફાળો", type: "aavak" },
  { name: "અનામત", type: "aavak" },
  { name: "અન્ય આવક", type: "aavak" },
  { name: "પરચુરણ આવક", type: "aavak" },

  // ================= જાવક (JAVAK) =================
  { name: "કર્મચારી પગાર ખર્ચ", type: "javak" },
  { name: "પંચાયત ઘર નિભાવણી તથા ફનીચર ખર્ચ", type: "javak" },
  { name: "વોટર વર્કસ નિભાવણી", type: "javak" },
  { name: "પાઈપ લાઈન નિભાવણી", type: "javak" },
  { name: "સ્ટ્રીટ લાઈટ બીલ", type: "javak" },
  { name: "સ્ટ્રીટ લાઈટ મરામત ખર્ચ", type: "javak" },
  { name: "સફાઈ ખર્ચ", type: "javak" },
  { name: "ગટર લાઈન નિભાવણી", type: "javak" },
  { name: "ઓફીસ સાદિલવાર ખર્ચ", type: "javak" },
  { name: "સ્ટેશનરી અને કંટીજન્સી / ઝેરોક્ષ ખર્ચ", type: "javak" },
  { name: "કમ્પ્યુટર નિભાવણી ખર્ચ", type: "javak" },
  { name: "વી.સી.ઈ મહેનતાણું / જી.ઈ.બી કમિશન", type: "javak" },
  { name: "જાહેર આરોગ્ય ખર્ચ", type: "javak" },
  { name: "રાષ્ટ્રિય તહેવાર ઉજવણી ખર્ચ", type: "javak" },
  { name: "બેંક ખર્ચ", type: "javak" },
  { name: "સી.સી રોડ ખર્ચ", type: "javak" },
  { name: "પેવર બ્લોક ખર્ચ", type: "javak" },
  { name: "રસ્તા દુરસ્તી ખર્ચ", type: "javak" },
  { name: "નવીન પાણી ની પાઈપ ખર્ચ", type: "javak" },
  { name: "નવીન / ગંદા પાણી ગટર લાઈન ખર્ચ", type: "javak" },
  { name: "સ્મશાન ગૃહ ખર્ચ", type: "javak" },
  { name: "સંરક્ષણ દિવાલ / વરંડો", type: "javak" },
  { name: "એપ્રોચ રોડ ખર્ચ", type: "javak" },
  { name: "અનામત પરત", type: "javak" },
  { name: "પરચુરણ ખર્ચ", type: "javak" },
];
